"""Add metadata column to study

Revision ID: 15e0ed881953
Revises: 0011
Create Date: 2026-03-15 23:39:24.179379

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '15e0ed881953'
down_revision: str | None = '0011'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study', sa.Column('metadata', sa.JSON(), nullable=True, comment='Flexible study metadata (objectives, questions)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study', 'metadata')
    # ### end Alembic commands ###
