"""add_user_security_preference_columns

Revision ID: 2f51665cbb6d
Revises: 15e0ed881953
Create Date: 2026-03-16 08:37:14.505559

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2f51665cbb6d'
down_revision: str | None = '15e0ed881953'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_code',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hashed_code', sa.String(length=255), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backup_code_user_id'), 'backup_code', ['user_id'], unique=False)
    op.create_table('security_audit_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('PASSWORD_CHANGED', 'TOTP_ENABLED', 'TOTP_DISABLED', 'BACKUP_CODES_REGENERATED', 'TOTP_LOCKED', name='security_event_type_enum'), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_audit_event_user_id'), 'security_audit_event', ['user_id'], unique=False)
    op.add_column('user', sa.Column('theme_preference', sa.Enum('LIGHT', 'DARK', 'SYSTEM', name='theme_preference_enum'), server_default='system', nullable=False))
    op.add_column('user', sa.Column('token_version', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user', sa.Column('totp_enabled', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('user', sa.Column('totp_secret_encrypted', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('totp_failed_attempts', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user', sa.Column('totp_locked_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user', sa.Column('password_changed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'password_changed_at')
    op.drop_column('user', 'totp_locked_until')
    op.drop_column('user', 'totp_failed_attempts')
    op.drop_column('user', 'totp_secret_encrypted')
    op.drop_column('user', 'totp_enabled')
    op.drop_column('user', 'token_version')
    op.drop_column('user', 'theme_preference')
    op.drop_index(op.f('ix_security_audit_event_user_id'), table_name='security_audit_event')
    op.drop_table('security_audit_event')
    op.drop_index(op.f('ix_backup_code_user_id'), table_name='backup_code')
    op.drop_table('backup_code')
    # ### end Alembic commands ###
