/**
 * TanStack Query hooks for the Rapid Review evidence briefing API (feature 008).
 *
 * Includes polling when any briefing is still being generated (no pdf_available yet).
 */

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import {
  createShareToken,
  generateBriefing,
  listBriefings,
  publishBriefing,
  revokeShareToken,
  type BriefingDetail,
  type BriefingSummary,
  type GenerateBriefingResponse,
  type ShareToken,
} from '../../services/rapid/briefingApi';

// ---------------------------------------------------------------------------
// Query keys
// ---------------------------------------------------------------------------

/** @returns TanStack Query key for a study's briefing list. */
export function rrBriefingsKey(studyId: number): [string, number] {
  return ['rr-briefings', studyId];
}

// ---------------------------------------------------------------------------
// Hooks
// ---------------------------------------------------------------------------

/**
 * Query hook for all evidence briefing versions for a study.
 *
 * Polls every 3 seconds when any briefing does not yet have a PDF available
 * (i.e., still being generated by the background job).
 *
 * @param studyId - The integer study ID.
 * @returns TanStack Query result for the briefing list.
 */
export function useBriefings(studyId: number) {
  return useQuery<BriefingSummary[]>({
    queryKey: rrBriefingsKey(studyId),
    queryFn: () => listBriefings(studyId),
    enabled: studyId > 0,
    refetchInterval: (query) => {
      const briefings = query.state.data;
      if (!briefings) return false;
      const anyGenerating = briefings.some((b) => !b.pdf_available);
      return anyGenerating ? 3000 : false;
    },
  });
}

/**
 * Mutation hook for generating a new evidence briefing version.
 *
 * Invalidates the briefings query on success so polling begins immediately.
 *
 * @param studyId - The integer study ID.
 * @returns TanStack mutation object.
 */
export function useGenerateBriefing(studyId: number) {
  const queryClient = useQueryClient();
  return useMutation<GenerateBriefingResponse, Error, void>({
    mutationFn: () => generateBriefing(studyId),
    onSuccess: () => {
      void queryClient.invalidateQueries({ queryKey: rrBriefingsKey(studyId) });
    },
  });
}

/**
 * Mutation hook for publishing a draft briefing.
 *
 * Invalidates the briefings query on success.
 *
 * @param studyId - The integer study ID.
 * @returns TanStack mutation object where the variable is the briefing ID.
 */
export function usePublishBriefing(studyId: number) {
  const queryClient = useQueryClient();
  return useMutation<BriefingDetail, Error, number>({
    mutationFn: (briefingId) => publishBriefing(studyId, briefingId),
    onSuccess: () => {
      void queryClient.invalidateQueries({ queryKey: rrBriefingsKey(studyId) });
    },
  });
}

/**
 * Mutation hook for creating a share token for a published briefing.
 *
 * @param studyId - The integer study ID.
 * @returns TanStack mutation object where the variable is the briefing ID.
 */
export function useCreateShareToken(studyId: number) {
  return useMutation<ShareToken, Error, number>({
    mutationFn: (briefingId) => createShareToken(studyId, briefingId),
  });
}

/**
 * Mutation hook for revoking a share token.
 *
 * Invalidates the briefings query on success.
 *
 * @param studyId - The integer study ID.
 * @returns TanStack mutation object where the variable is the token string.
 */
export function useRevokeShareToken(studyId: number) {
  const queryClient = useQueryClient();
  return useMutation<void, Error, string>({
    mutationFn: (token) => revokeShareToken(studyId, token),
    onSuccess: () => {
      void queryClient.invalidateQueries({ queryKey: rrBriefingsKey(studyId) });
    },
  });
}
