"""MCP search tools: fan-out search_papers, per-source search tools, and get_paper.

The upgraded ``search_papers`` fans out across all SourceRegistry-enabled sources
concurrently via :func:`asyncio.gather`, deduplicates results, and records any
partial failures in ``sources_failed``.

Per-source tools (``search_ieee``, ``search_scopus``, etc.) allow agents to
query individual databases directly.
"""

from __future__ import annotations

import asyncio
from typing import Any

import httpx
from fastmcp import FastMCP
from pydantic import BaseModel

from researcher_mcp.core.config import get_settings
from researcher_mcp.core.dedup import deduplicate_paper_records
from researcher_mcp.core.http_client import make_retry_client
from researcher_mcp.core.registry import get_registry
from researcher_mcp.sources.base import PaperRecord
from researcher_mcp.sources.crossref import CrossRefSource
from researcher_mcp.sources.open_alex import OpenAlexSource
from researcher_mcp.sources.semantic_scholar import SemanticScholarSource

mcp: FastMCP = FastMCP("researcher-mcp")

# ---------------------------------------------------------------------------
# Shared response schemas
# ---------------------------------------------------------------------------


class SourceFailure(BaseModel):
    """Record of a database source that failed during fan-out search.

    Attributes:
        source: Database index identifier (e.g. ``"ieee_xplore"``).
        reason: Short reason string (e.g. ``"rate_limited"``, ``"unreachable"``).

    """

    source: str
    reason: str


class SearchPapersResult(BaseModel):
    """Result of a fan-out multi-database paper search.

    Attributes:
        papers: Deduplicated list of :class:`PaperRecord` objects.
        total_found: Number of unique papers found before truncation.
        sources_queried: List of database index identifiers that were queried.
        sources_failed: List of sources that raised exceptions during the search.
        truncated: True when ``total_found`` exceeds ``max_results``.

    """

    papers: list[PaperRecord]
    total_found: int
    sources_queried: list[str]
    sources_failed: list[SourceFailure]
    truncated: bool


class SemanticScholarPaperDetail(PaperRecord):
    """Extended paper record with Semantic Scholar-specific fields.

    Attributes:
        tldr: One-sentence summary generated by the Semantic Scholar model.
        influential_citation_count: Number of influential citations.
        is_open_access: Whether the paper is openly accessible.
        fields_of_study: List of academic fields the paper belongs to.

    """

    tldr: str | None = None
    influential_citation_count: int = 0
    is_open_access: bool = False
    fields_of_study: list[str] = []


# ---------------------------------------------------------------------------
# Legacy singletons for get_paper (DOI-cascade via CrossRef → SS → OA)
# ---------------------------------------------------------------------------

_legacy_client: httpx.AsyncClient | None = None
_legacy_ss: SemanticScholarSource | None = None
_legacy_oa: OpenAlexSource | None = None
_legacy_cr: CrossRefSource | None = None


def _get_legacy_sources() -> tuple[SemanticScholarSource, OpenAlexSource, CrossRefSource]:
    """Return (lazily created) legacy source singletons for get_paper.

    Returns:
        Tuple of (SemanticScholarSource, OpenAlexSource, CrossRefSource).

    """
    global _legacy_client, _legacy_ss, _legacy_oa, _legacy_cr
    if _legacy_client is None:
        settings = get_settings()
        _legacy_client = make_retry_client()
        _legacy_ss = SemanticScholarSource(_legacy_client, rpm=settings.semantic_scholar_rpm)
        _legacy_oa = OpenAlexSource(_legacy_client, rpm=settings.open_alex_rpm)
        _legacy_cr = CrossRefSource(_legacy_client)
    assert _legacy_ss is not None and _legacy_oa is not None and _legacy_cr is not None
    return _legacy_ss, _legacy_oa, _legacy_cr


# ---------------------------------------------------------------------------
# Fan-out helper
# ---------------------------------------------------------------------------


async def _search_one(
    index: str,
    source: Any,
    query: str,
    max_results: int,
    year_from: int | None,
    year_to: int | None,
) -> tuple[str, list[PaperRecord] | None, str | None]:
    """Search a single source, returning (index, papers_or_None, error_or_None).

    Args:
        index: Database index identifier.
        source: DatabaseSource instance.
        query: Search query string.
        max_results: Maximum results to request.
        year_from: Earliest publication year filter.
        year_to: Latest publication year filter.

    Returns:
        Tuple of ``(index, results, error_reason)`` — exactly one of
        ``results`` or ``error_reason`` will be non-None.

    """
    try:
        results = await source.search(
            query, max_results=max_results, year_from=year_from, year_to=year_to
        )
        return (index, results, None)
    except Exception as exc:  # noqa: BLE001
        reason = _classify_error(exc)
        return (index, None, reason)


def _classify_error(exc: Exception) -> str:
    """Convert an exception into a short reason string.

    Args:
        exc: The exception that was raised by a source.

    Returns:
        A short classification string suitable for :class:`SourceFailure.reason`.

    """
    msg = str(exc).lower()
    if "401" in msg or "403" in msg or "auth" in msg or "unauthorized" in msg:
        return "auth_failed"
    if "429" in msg or "rate" in msg:
        return "rate_limited"
    if "timeout" in msg or "connect" in msg or "transport" in msg:
        return "unreachable"
    return "unreachable"


# ---------------------------------------------------------------------------
# Upgraded fan-out search_papers (T025)
# ---------------------------------------------------------------------------


@mcp.tool()
async def search_papers(
    query: str,
    indices: list[str] | None = None,
    max_results: int = 100,
    year_from: int | None = None,
    year_to: int | None = None,
) -> SearchPapersResult:
    """Fan-out search across all configured academic database indices.

    Queries all enabled sources concurrently via :func:`asyncio.gather`.
    Results are merged and deduplicated (DOI primary key; normalised
    title+first-author fallback).  Sources that fail are recorded in
    ``sources_failed`` but do not abort the overall search.

    Args:
        query: Free-text or boolean search query.
        indices: Optional list of :class:`DatabaseIndex` values to query.
            Pass ``None`` to query all registered sources.
        max_results: Maximum total papers to return after deduplication.
        year_from: Earliest publication year filter (inclusive).
        year_to: Latest publication year filter (inclusive).

    Returns:
        A :class:`SearchPapersResult` with merged, deduplicated papers and
        per-source failure records.

    """
    registry = get_registry()
    enabled = registry.get_enabled(indices)

    tasks = [_search_one(idx, src, query, max_results, year_from, year_to) for idx, src in enabled]
    raw_results = await asyncio.gather(*tasks)

    all_papers: list[PaperRecord] = []
    failures: list[SourceFailure] = []
    sources_queried: list[str] = []

    for index, papers, reason in raw_results:
        sources_queried.append(index)
        if papers is not None:
            all_papers.extend(papers)
        else:
            failures.append(SourceFailure(source=index, reason=reason or "unreachable"))

    deduped = deduplicate_paper_records(all_papers)
    total_found = len(deduped)
    truncated = total_found > max_results
    papers_out = deduped[:max_results]

    return SearchPapersResult(
        papers=papers_out,
        total_found=total_found,
        sources_queried=sources_queried,
        sources_failed=failures,
        truncated=truncated,
    )


# ---------------------------------------------------------------------------
# Legacy get_paper (DOI-cascade: CrossRef → SS → OA)
# ---------------------------------------------------------------------------


@mcp.tool()
async def get_paper(
    paper_id: str,
    fields: list[str] | None = None,
) -> dict[str, Any]:
    """Retrieve full metadata for a single paper.

    For DOI-prefixed IDs (``DOI:10.xxxx/...``), CrossRef is queried first
    for enrichment; falls back through Semantic Scholar → OpenAlex.

    Args:
        paper_id: Semantic Scholar paper ID or DOI (prefix with ``DOI:``).
        fields: Fields to return.

    Returns:
        Dict matching the paper metadata schema.

    """
    ss, oa, cr = _get_legacy_sources()
    warnings: list[str] = []

    if paper_id.startswith("DOI:"):
        doi = paper_id[4:]
        try:
            cr_data = await cr.resolve_doi(doi)
            warnings.extend(cr_data.get("warnings", []))
            try:
                ss_data = await ss.get_paper(paper_id, fields)
                ss_data["warnings"] = warnings + ss_data.get("warnings", [])
                return ss_data
            except httpx.HTTPStatusError, httpx.TransportError, httpx.TimeoutException:
                cr_data["warnings"] = warnings
                return cr_data
        except httpx.HTTPStatusError, httpx.TransportError, httpx.TimeoutException:
            pass

    try:
        return await ss.get_paper(paper_id, fields)
    except httpx.HTTPStatusError, httpx.TransportError, httpx.TimeoutException:
        result = await oa.get_paper(paper_id, fields)
        return result


# ---------------------------------------------------------------------------
# T026: IEEE Xplore per-source tools
# ---------------------------------------------------------------------------


@mcp.tool()
async def search_ieee(
    query: str,
    max_results: int = 100,
    year_from: int | None = None,
    year_to: int | None = None,
    content_type: list[str] | None = None,
) -> list[PaperRecord]:
    """Search IEEE Xplore for papers matching *query*.

    Args:
        query: Free-text or boolean search string.
        max_results: Maximum results to return (up to 200).
        year_from: Earliest publication year filter.
        year_to: Latest publication year filter.
        content_type: Optional filter list (e.g. ``["Journals","Conference Publications"]``).

    Returns:
        List of :class:`PaperRecord` objects from IEEE Xplore.

    """
    registry = get_registry()
    source = registry.get("ieee_xplore")
    if source is None:
        return []
    return await source.search(query, max_results=max_results, year_from=year_from, year_to=year_to)


@mcp.tool()
async def get_ieee_paper(article_number: str) -> PaperRecord | None:
    """Retrieve a single IEEE Xplore paper by article number.

    Args:
        article_number: The IEEE-native article number identifier string.

    Returns:
        A :class:`PaperRecord` if found, or ``None``.

    """
    from researcher_mcp.sources.ieee import IEEESource  # noqa: PLC0415

    registry = get_registry()
    source = registry.get("ieee_xplore")
    if source is None or not isinstance(source, IEEESource):
        return None
    return await source.get_paper_by_article_number(article_number)


# ---------------------------------------------------------------------------
# T027: ACM DL, Google Scholar, Inspec per-source tools
# ---------------------------------------------------------------------------


@mcp.tool()
async def search_acm(
    query: str,
    max_results: int = 100,
    year_from: int | None = None,
    year_to: int | None = None,
) -> dict[str, Any]:
    """Search the ACM Digital Library for papers matching *query*.

    Returns an ``AcmSearchResult``-shaped dict with ``papers`` and ``truncated``
    fields.  Rate limiting may result in fewer results than requested.

    Args:
        query: Keyword search query.
        max_results: Maximum records to request.
        year_from: Earliest publication year filter.
        year_to: Latest publication year filter.

    Returns:
        Dict with ``papers`` (list of :class:`PaperRecord`) and ``truncated`` bool.

    """
    registry = get_registry()
    source = registry.get("acm_dl")
    if source is None:
        return {"papers": [], "truncated": False}
    papers = await source.search(
        query, max_results=max_results, year_from=year_from, year_to=year_to
    )
    truncated = len(papers) == max_results
    return {"papers": [p.model_dump() for p in papers], "truncated": truncated}


@mcp.tool()
async def search_google_scholar(
    query: str,
    max_results: int = 100,
    year_from: int | None = None,
    year_to: int | None = None,
) -> list[PaperRecord]:
    """Search Google Scholar for papers matching *query*.

    Uses the ``scholarly`` library.  Requires a proxy (``SCHOLARLY_PROXY_URL``)
    to avoid CAPTCHA blocks in production.

    Args:
        query: Free-text search query.
        max_results: Maximum results to return.
        year_from: Earliest publication year filter.
        year_to: Latest publication year filter.

    Returns:
        List of :class:`PaperRecord` objects from Google Scholar.

    """
    registry = get_registry()
    source = registry.get("google_scholar")
    if source is None:
        return []
    return await source.search(query, max_results=max_results, year_from=year_from, year_to=year_to)


@mcp.tool()
async def search_inspec(
    query: str,
    max_results: int = 100,
    year_from: int | None = None,
    year_to: int | None = None,
    databases: list[str] | None = None,
) -> list[PaperRecord]:
    """Search the Inspec / Engineering Village database for papers.

    Requires ``ELSEVIER_API_KEY`` (and optionally ``ELSEVIER_INST_TOKEN``).

    Args:
        query: Keyword or boolean search string.
        max_results: Maximum records to return.
        year_from: Earliest publication year filter.
        year_to: Latest publication year filter.
        databases: EV database codes to search (default: ``["INS", "CPX"]``).

    Returns:
        List of :class:`PaperRecord` objects from Inspec.

    """
    from researcher_mcp.sources.inspec import InspecSource  # noqa: PLC0415

    registry = get_registry()
    source = registry.get("inspec")
    if source is None or not isinstance(source, InspecSource):
        return []
    return await source.search(
        query,
        max_results=max_results,
        year_from=year_from,
        year_to=year_to,
        databases=databases,
    )


# ---------------------------------------------------------------------------
# T028: Scopus, WoS, ScienceDirect, Springer per-source tools
# ---------------------------------------------------------------------------


@mcp.tool()
async def search_scopus(
    query: str,
    max_results: int = 100,
    year_from: int | None = None,
    year_to: int | None = None,
    subject_areas: list[str] | None = None,
) -> list[PaperRecord]:
    """Search the Scopus abstract and citation database.

    Requires ``ELSEVIER_API_KEY``.

    Args:
        query: Scopus query string (supports field tags like ``TITLE-ABS-KEY``).
        max_results: Maximum records to return.
        year_from: Earliest publication year filter.
        year_to: Latest publication year filter.
        subject_areas: Optional list of Scopus subject area codes.

    Returns:
        List of :class:`PaperRecord` objects from Scopus.

    """
    from researcher_mcp.sources.scopus import ScopusSource  # noqa: PLC0415

    registry = get_registry()
    source = registry.get("scopus")
    if source is None or not isinstance(source, ScopusSource):
        return []
    return await source.search(
        query,
        max_results=max_results,
        year_from=year_from,
        year_to=year_to,
        subject_areas=subject_areas,
    )


@mcp.tool()
async def get_scopus_paper(
    doi: str | None = None,
    eid: str | None = None,
) -> PaperRecord | None:
    """Retrieve a single paper from Scopus by DOI or EID.

    Args:
        doi: Paper DOI (without ``https://doi.org/`` prefix).
        eid: Scopus EID identifier (alternative to DOI).

    Returns:
        A :class:`PaperRecord` if found, or ``None``.

    """
    from researcher_mcp.sources.scopus import ScopusSource  # noqa: PLC0415

    registry = get_registry()
    source = registry.get("scopus")
    if source is None or not isinstance(source, ScopusSource):
        return None
    identifier = doi or eid
    if not identifier:
        return None
    return await source.get_paper(identifier)


@mcp.tool()
async def search_wos(
    query: str,
    max_results: int = 100,
    year_from: int | None = None,
    year_to: int | None = None,
    edition: str | None = None,
) -> list[PaperRecord]:
    """Search the Web of Science database.

    Requires ``WOS_API_KEY`` (Clarivate WoS Starter API key).

    Args:
        query: WoS query string (supports field tags like ``TS=``, ``TI=``).
        max_results: Maximum records to return.
        year_from: Earliest publication year filter.
        year_to: Latest publication year filter.
        edition: WoS edition (``"WOS"``, ``"MEDLINE"``, ``"BIOSIS"``).

    Returns:
        List of :class:`PaperRecord` objects from Web of Science.

    """
    registry = get_registry()
    source = registry.get("web_of_science")
    if source is None:
        return []
    from researcher_mcp.sources.wos import WoSSource  # noqa: PLC0415

    if not isinstance(source, WoSSource):
        return []
    return await source.search(
        query,
        max_results=max_results,
        year_from=year_from,
        year_to=year_to,
        edition=edition,
    )


@mcp.tool()
async def search_sciencedirect(
    query: str,
    max_results: int = 100,
    year_from: int | None = None,
    year_to: int | None = None,
    open_access_only: bool = False,
) -> list[PaperRecord]:
    """Search the ScienceDirect full-text database.

    Requires ``ELSEVIER_API_KEY``.

    Args:
        query: Free-text or boolean query string.
        max_results: Maximum records to return.
        year_from: Earliest publication year filter.
        year_to: Latest publication year filter.
        open_access_only: If True, restrict to open-access articles.

    Returns:
        List of :class:`PaperRecord` objects from ScienceDirect.

    """
    from researcher_mcp.sources.science_direct import ScienceDirectSource  # noqa: PLC0415

    registry = get_registry()
    source = registry.get("science_direct")
    if source is None or not isinstance(source, ScienceDirectSource):
        return []
    return await source.search(
        query,
        max_results=max_results,
        year_from=year_from,
        year_to=year_to,
        open_access_only=open_access_only,
    )


@mcp.tool()
async def search_springer(
    query: str,
    max_results: int = 100,
    year_from: int | None = None,
    year_to: int | None = None,
    open_access_only: bool = False,
) -> list[PaperRecord]:
    """Search the SpringerLink database via the SpringerNature Metadata API.

    Requires ``SPRINGER_API_KEY``.

    Args:
        query: Free-text search query.
        max_results: Maximum records to return.
        year_from: Earliest publication year filter.
        year_to: Latest publication year filter.
        open_access_only: If True, restrict to open-access content.

    Returns:
        List of :class:`PaperRecord` objects from SpringerLink.

    """
    from researcher_mcp.sources.springer import SpringerSource  # noqa: PLC0415

    registry = get_registry()
    source = registry.get("springer_link")
    if source is None or not isinstance(source, SpringerSource):
        return []
    return await source.search(
        query,
        max_results=max_results,
        year_from=year_from,
        year_to=year_to,
        open_access_only=open_access_only,
    )


# ---------------------------------------------------------------------------
# T029: Semantic Scholar dedicated tools
# ---------------------------------------------------------------------------


@mcp.tool()
async def search_semantic_scholar(
    query: str,
    max_results: int = 100,
    year_from: int | None = None,
    year_to: int | None = None,
    fields_of_study: list[str] | None = None,
    open_access_only: bool = False,
) -> list[PaperRecord]:
    """Search Semantic Scholar for papers matching *query*.

    Delegates to the :class:`SemanticScholarSource` registered in the default
    registry.

    Args:
        query: Free-text search query.
        max_results: Maximum results to return.
        year_from: Earliest publication year filter.
        year_to: Latest publication year filter.
        fields_of_study: Optional list of academic field strings to filter.
        open_access_only: If True, restrict to open-access papers.

    Returns:
        List of :class:`PaperRecord` objects from Semantic Scholar.

    """
    registry = get_registry()
    source = registry.get("semantic_scholar")
    if source is None:
        return []
    return await source.search(query, max_results=max_results, year_from=year_from, year_to=year_to)


@mcp.tool()
async def get_paper_semantic_scholar(
    doi: str | None = None,
    semantic_scholar_id: str | None = None,
) -> dict[str, Any]:
    """Retrieve detailed metadata for a single paper from Semantic Scholar.

    Args:
        doi: Paper DOI without the ``https://doi.org/`` prefix.
        semantic_scholar_id: Semantic Scholar paper ID (alternative to DOI).

    Returns:
        Dict with paper metadata including ``tldr``, ``influentialCitationCount``,
        ``isOpenAccess``, and ``fieldsOfStudy`` from the Semantic Scholar API.

    """
    ss, _, _ = _get_legacy_sources()
    paper_id = f"DOI:{doi}" if doi else (semantic_scholar_id or "")
    if not paper_id:
        return {"error": "Must provide either doi or semantic_scholar_id"}
    fields = [
        "title",
        "abstract",
        "externalIds",
        "year",
        "authors",
        "venue",
        "isOpenAccess",
        "fieldsOfStudy",
        "tldr",
        "influentialCitationCount",
    ]
    return await ss.get_paper(paper_id, fields)
